export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { code: 'SA', name: 'السعودية', flag: '🇸🇦' },
  { code: 'AE', name: 'الإمارات', flag: '🇦🇪' },
  { code: 'EG', name: 'مصر', flag: '🇪🇬' },
  { code: 'DZ', name: 'الجزائر', flag: '🇩🇿' },
  { code: 'MA', name: 'المغرب', flag: '🇲🇦' },
  { code: 'TN', name: 'تونس', flag: '🇹🇳' },
  { code: 'LY', name: 'ليبيا', flag: '🇱🇾' },
  { code: 'SD', name: 'السودان', flag: '🇸🇩' },
  { code: 'IQ', name: 'العراق', flag: '🇮🇶' },
  { code: 'SY', name: 'سوريا', flag: '🇸🇾' },
  { code: 'JO', name: 'الأردن', flag: '🇯🇴' },
  { code: 'LB', name: 'لبنان', flag: '🇱🇧' },
  { code: 'PS', name: 'فلسطين', flag: '🇵🇸' },
  { code: 'YE', name: 'اليمن', flag: '🇾🇪' },
  { code: 'OM', name: 'عُمان', flag: '🇴🇲' },
  { code: 'QA', name: 'قطر', flag: '🇶🇦' },
  { code: 'KW', name: 'الكويت', flag: '🇰🇼' },
  { code: 'BH', name: 'البحرين', flag: '🇧🇭' },
  { code: 'MR', name: 'موريتانيا', flag: '🇲🇷' },
  { code: 'DJ', name: 'جيبوتي', flag: '🇩🇯' },
  { code: 'KM', name: 'جزر القمر', flag: '🇰🇲' },
  { code: 'SO', name: 'الصومال', flag: '🇸🇴' },
  { code: 'TD', name: 'تشاد', flag: '🇹🇩' },
  { code: 'TR', name: 'تركيا', flag: '🇹🇷' },
  { code: 'PK', name: 'باكستان', flag: '🇵🇰' },
  { code: 'IN', name: 'الهند', flag: '🇮🇳' },
  { code: 'ID', name: 'إندونيسيا', flag: '🇮🇩' },
  { code: 'MY', name: 'ماليزيا', flag: '🇲🇾' },
  { code: 'IR', name: 'إيران', flag: '🇮🇷' },
  { code: 'AF', name: 'أفغانستان', flag: '🇦🇫' },
  { code: 'BD', name: 'بنغلاديش', flag: '🇧🇩' },
  { code: 'AZ', name: 'أذربيجان', flag: '🇦🇿' },
  { code: 'KZ', name: 'كازاخستان', flag: '🇰🇿' },
  { code: 'UZ', name: 'أوزبكستان', flag: '🇺🇿' },
  { code: 'TM', name: 'تركمانستان', flag: '🇹🇲' },
  { code: 'KG', name: 'قيرغيزستان', flag: '🇰🇬' },
  { code: 'TJ', name: 'طاجيكستان', flag: '🇹🇯' },
  { code: 'AL', name: 'ألبانيا', flag: '🇦🇱' },
  { code: 'BA', name: 'البوسنة والهرسك', flag: '🇧🇦' },
  { code: 'XK', name: 'كوسوفو', flag: '🇽🇰' },
  { code: 'MV', name: 'المالديف', flag: '🇲🇻' },
  { code: 'BN', name: 'بروناي', flag: '🇧🇳' },
  { code: 'SN', name: 'السنغال', flag: '🇸🇳' },
  { code: 'ML', name: 'مالي', flag: '🇲🇱' },
  { code: 'NE', name: 'النيجر', flag: '🇳🇪' },
  { code: 'BF', name: 'بوركينا فاسو', flag: '🇧🇫' },
  { code: 'GN', name: 'غينيا', flag: '🇬🇳' },
  { code: 'SL', name: 'سيراليون', flag: '🇸🇱' },
  { code: 'GM', name: 'غامبيا', flag: '🇬🇲' },
  { code: 'CI', name: 'ساحل العاج', flag: '🇨🇮' },
  { code: 'TG', name: 'توغو', flag: '🇹🇬' },
  { code: 'CM', name: 'الكاميرون', flag: '🇨🇲' },
  { code: 'UG', name: 'أوغندا', flag: '🇺🇬' },
  { code: 'TZ', name: 'تنزانيا', flag: '🇹🇿' },
  { code: 'GW', name: 'غينيا بيساو', flag: '🇬🇼' },
  { code: 'ER', name: 'إريتريا', flag: '🇪🇷' },
  { code: 'BJ', name: 'بنين', flag: '🇧🇯' },
  { code: 'GA', name: 'الغابون', flag: '🇬🇦' },
  { code: 'US', name: 'الولايات المتحدة', flag: '🇺🇸' },
  { code: 'CA', name: 'كندا', flag: '🇨🇦' },
  { code: 'GB', name: 'بريطانيا', flag: '🇬🇧' },
  { code: 'FR', name: 'فرنسا', flag: '🇫🇷' },
  { code: 'DE', name: 'ألمانيا', flag: '🇩🇪' },
  { code: 'IT', name: 'إيطاليا', flag: '🇮🇹' },
  { code: 'ES', name: 'إسبانيا', flag: '🇪🇸' },
  { code: 'NL', name: 'هولندا', flag: '🇳🇱' },
  { code: 'BE', name: 'بلجيكا', flag: '🇧🇪' },
  { code: 'SE', name: 'السويد', flag: '🇸🇪' },
  { code: 'NO', name: 'النرويج', flag: '🇳🇴' },
  { code: 'AT', name: 'النمسا', flag: '🇦🇹' },
  { code: 'CH', name: 'سويسرا', flag: '🇨🇭' },
  { code: 'AU', name: 'أستراليا', flag: '🇦🇺' },
  { code: 'NZ', name: 'نيوزيلندا', flag: '🇳🇿' },
  { code: 'BR', name: 'البرازيل', flag: '🇧🇷' },
  { code: 'AR', name: 'الأرجنتين', flag: '🇦🇷' },
  { code: 'ET', name: 'إثيوبيا', flag: '🇪🇹' },
  { code: 'NG', name: 'نيجيريا', flag: '🇳🇬' },
  { code: 'RU', name: 'روسيا', flag: '🇷🇺' },
  { code: 'CN', name: 'الصين', flag: '🇨🇳' },
  { code: 'JP', name: 'اليابان', flag: '🇯🇵' },
  { code: 'KR', name: 'كوريا الجنوبية', flag: '🇰🇷' },
  { code: 'MX', name: 'المكسيك', flag: '🇲🇽' },
  { code: 'TH', name: 'تايلاند', flag: '🇹🇭' },
  { code: 'PH', name: 'الفلبين', flag: '🇵🇭' },
  { code: 'LK', name: 'سريلانكا', flag: '🇱🇰' },
  { code: 'GR', name: 'اليونان', flag: '🇬🇷' },
  { code: 'DK', name: 'الدنمارك', flag: '🇩🇰' },
  { code: 'FI', name: 'فنلندا', flag: '🇫🇮' },
  { code: 'IE', name: 'أيرلندا', flag: '🇮🇪' },
  { code: 'PT', name: 'البرتغال', flag: '🇵🇹' },
  { code: 'PL', name: 'بولندا', flag: '🇵🇱' },
  { code: 'CZ', name: 'التشيك', flag: '🇨🇿' },
  { code: 'RO', name: 'رومانيا', flag: '🇷🇴' },
  { code: 'HU', name: 'المجر', flag: '🇭🇺' },
  { code: 'UA', name: 'أوكرانيا', flag: '🇺🇦' },
  { code: 'IL', name: 'إسرائيل', flag: '🇮🇱' },
  { code: 'ZA', name: 'جنوب إفريقيا', flag: '🇿🇦' },
  { code: 'KE', name: 'كينيا', flag: '🇰🇪' },
  { code: 'GH', name: 'غانا', flag: '🇬🇭' },
];

export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}